#!/usr/bin/perl -w

use strict;

use Text::Diff;

$| = 1;

die "ERROR: diff file1 file2\n" if !defined $ARGV[0] || !defined $ARGV[1];

print diff($ARGV[0], $ARGV[1], { 'STYLE' => 'OldStyle' });
