# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Unit Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        run: |
          PYTHONPATH=./python/lib python -m unittest python/lib/indent.py
          PYTHONPATH=./python/lib python -m unittest python/lib/reutil.py
          PYTHONPATH=./python/lib python -m unittest python/lib/time.py 
          PYTHONPATH=./python/lib python -m unittest python/lib/util.py
          PYTHONPATH=./python/lib python -m unittest python/lib/xml/domutil.py 
          PYTHONPATH=./python/lib python -m unittest python/lib/xml/util.py
