# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#create-an-example-workflow

name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g bats
      - run: bats -v


runs:
  using: 'node20'
